import { useState, useEffect } from "react";
import SavedSummaryCard from "../components/SavedSummaryCard";

const SavedSummariesPage = () => {
  const [savedSummaries, setSavedSummaries] = useState([]);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    // Fetch saved summaries from backend
    const fetchSavedSummaries = async () => {
      setIsLoading(true);
      try {
        // Replace with actual API call
        const mockData = [
          {
            id: "1",
            articleId: "1",
            title: "Saved Summary Example",
            summary:
              "This is an example of a saved summary generated by Gemini AI. The actual implementation would fetch these from your backend.",
            source: "Example News",
            savedAt: new Date().toISOString(),
            originalUrl: "#",
          },
        ];
        setSavedSummaries(mockData);
      } catch (error) {
        console.error("Error fetching saved summaries:", error);
      } finally {
        setIsLoading(false);
      }
    };

    fetchSavedSummaries();
  }, []);

  return (
    <div>
      <div className="mb-8">
        <h1 className="text-3xl font-bold text-dark mb-2">
          Your Saved Summaries
        </h1>
        <p className="text-gray-600">
          Access your previously saved news summaries
        </p>
      </div>

      {isLoading ? (
        <div className="flex justify-center items-center h-64">
          <div className="animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-primary"></div>
        </div>
      ) : savedSummaries.length === 0 ? (
        <div className="bg-light rounded-lg p-8 text-center">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            className="h-12 w-12 mx-auto text-gray-400 mb-4"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth={2}
              d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"
            />
          </svg>
          <h3 className="text-lg font-medium text-dark mb-2">
            No saved summaries yet
          </h3>
          <p className="text-gray-600">
            Summarize some news articles and save them for later!
          </p>
        </div>
      ) : (
        <div className="space-y-6">
          {savedSummaries.map((summary) => (
            <SavedSummaryCard key={summary.id} summary={summary} />
          ))}
        </div>
      )}
    </div>
  );
};

export default SavedSummariesPage;
